apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: vllm-monitor
spec:
  selector:
    matchLabels:
      serving.kserve.io/inferenceservice: <patch-me>
  podMetricsEndpoints:
    - port: "8000"
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - demo-llm
