# apiVersion: serving.kserve.io/v1alpha1
# kind: ServingRuntime
# metadata:
#   name: vllm-runtime
# spec:
#   annotations:
#     opendatahub.io/kserve-runtime: vllm
#     prometheus.io/path: /metrics
#     prometheus.io/port: '8000'
#   containers:
#     - args:
#         - '--port=8000'
#         - '--model=/mnt/models'
#         - '--served-model-name={{.Name}}'
#         - '--max-model-len=16000'
#       command:
#         - python
#         - '-m'
#         - vllm.entrypoints.openai.api_server
#       env:
#         - name: HF_HOME
#           value: /tmp/hf_home
#       image: 'registry.redhat.io/rhaiis/vllm-cuda-rhel9@sha256:ad756c01ec99a99cc7d93401c41b8d92ca96fb1ab7c5262919d818f2be4f3768'
#       name: kserve-container
#       ports:
#         - containerPort: 8000
#           protocol: TCP
#   multiModel: false
#   supportedModelFormats:
#     - autoSelect: true
#       name: vLLM

apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/template-display-name: vLLM NVIDIA GPU ServingRuntime for KServe
  labels:
    opendatahub.io/dashboard: "true"
  name: vllm-runtime
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8000"
    opendatahub.io/kserve-runtime: vllm
  containers:
  - args:
    - --port=8000
    - --model=/mnt/models
    command:
    - python
    - -m
    - vllm.entrypoints.openai.api_server
    env:
    - name: HF_HOME
      value: /tmp/hf_home
    image: 'registry.redhat.io/rhaiis/vllm-cuda-rhel9@sha256:ad756c01ec99a99cc7d93401c41b8d92ca96fb1ab7c5262919d818f2be4f3768'      
    # image: registry.redhat.io/rhoai/odh-vllm-cuda-rhel9:v2.25.0-1759340926
    name: kserve-container
    ports:
    - containerPort: 8000
      protocol: TCP
    volumeMounts:
    - mountPath: /dev/shm
      name: shm
  multiModel: false
  supportedModelFormats:
  - autoSelect: true
    name: vLLM
  volumes:
  - emptyDir:
      medium: Memory
      sizeLimit: 2Gi
    name: shm